<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Package Id -->
		<PackageId>Semicolon.Cil</PackageId>
		<Version>1.0.0</Version>
		<RootNamespace>Semicolon.Cil</RootNamespace>
		<PackageId>Semicolon.Cil</PackageId>
		<ImplicitUsings>enable</ImplicitUsings>
		<DebugType>portable</DebugType>
		<GenerateDependencyFile>false</GenerateDependencyFile>
		<GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
		<Authors>Semicolon</Authors>
		<Description>Cil Manipulation library</Description>
		
		<!--Platform targeting-->
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<EnableLinuxTargeting>true</EnableLinuxTargeting>
		<EnableMacOSTargeting>true</EnableMacOSTargeting>
		<!-- Constants -->
		<DefineConstants Condition="'$(OS)' == 'Windows_NT'">WINDOWS</DefineConstants>
		<DefineConstants Condition="'$(OS)' == 'Unix' And $(RuntimeIdentifier.StartsWith('linux'))">LINUX</DefineConstants>
		<DefineConstants Condition="'$(OS)' == 'Unix' And $(RuntimeIdentifier.StartsWith('osx'))">MACOS</DefineConstants>
	</PropertyGroup>
</Project>